# Generated by Django 2.1.7 on 2019-02-12 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['-created_at'], 'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty',
        ),
        migrations.AddField(
            model_name='faculty',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
