# Generated by Django 2.1.7 on 2019-02-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190212_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Marketing Manager'), (1, 'Administrator'), (2, 'Marketing Coordinator'), (3, 'Faculty Guest'), (4, 'Student')], default=4, verbose_name='role'),
        ),
    ]
