# Generated by Django 2.1.7 on 2019-02-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190212_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Marketing Manager'), (1, 'Administrator'), (2, 'Marketing Coordinator'), (3, 'Faculty Guest'), (4, 'Student')], null=True, verbose_name='role'),
        ),
    ]
