# Generated by Django 2.1.7 on 2019-02-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=15, verbose_name='academic year')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('closure_date', models.DateTimeField(verbose_name='closure date')),
                ('final_closure_date', models.DateTimeField(verbose_name='final closure date')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Published'), (1, 'Unpublished')], default=0, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'date',
                'verbose_name_plural': 'dates',
                'ordering': ['-academic_year'],
            },
        ),
    ]
