# Generated by Django 2.1.7 on 2019-02-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='academic_year',
            field=models.DateField(verbose_name='academic year'),
        ),
    ]
