# Generated by Django 2.1.7 on 2019-02-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_data', '0002_auto_20190214_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='academic_year',
            field=models.CharField(max_length=15, verbose_name='academic year'),
        ),
    ]
