# Generated by Django 2.1.7 on 2019-03-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_data', '0002_auto_20190323_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='academic_year',
            field=models.CharField(max_length=15, verbose_name='academic year'),
        ),
    ]
