# Generated by Django 2.1.7 on 2019-02-15 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_data', '0003_auto_20190214_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
