# Generated by Django 2.1.7 on 2019-02-15 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_data', '0004_date_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='slug',
        ),
    ]
