# Generated by Django 2.1.7 on 2019-02-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_data', '0005_remove_date_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Published'), (1, 'Unpublished')], default=0, verbose_name='status'),
        ),
    ]
