# Generated by Django 2.1.7 on 2019-04-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspicious', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspicious',
            name='ip',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ip address'),
        ),
    ]
