# Generated by Django 2.1.7 on 2019-03-02 08:34

import contribution.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('file', models.FileField(upload_to=contribution.utils.upload_contribution_path, verbose_name='file')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('is_commented', models.BooleanField(default=False, verbose_name='is commented')),
                ('is_selected', models.BooleanField(default=False, verbose_name='is selected')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_for', models.PositiveSmallIntegerField(choices=[(0, 'Documents'), (1, 'Images')], default=0, verbose_name='category for')),
                ('title', models.CharField(max_length=23, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Contribution Category',
                'verbose_name_plural': 'Contribution Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_category', to='contribution.ContributionCategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contribution', to='accounts.UserProfile', verbose_name='user'),
        ),
    ]
