# Generated by Django 2.1.7 on 2019-02-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='is selected'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='is selected'),
        ),
    ]
