# Generated by Django 2.1.7 on 2019-02-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='title',
            field=models.CharField(max_length=23, verbose_name='titles'),
        ),
    ]
