# Generated by Django 2.1.7 on 2019-04-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='special comment'),
        ),
    ]
