# Generated by Django 2.1.7 on 2019-02-15 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='category')),
                ('identifier', models.CharField(blank=True, max_length=200, null=True, verbose_name='identifier')),
                ('message', models.CharField(blank=True, max_length=200, null=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_created_by', to='accounts.UserProfile', verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-updated_at'],
            },
        ),
    ]
