# Generated by Django 2.1.7 on 2019-03-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='category')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='identifier')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject')),
                ('message', models.TextField(blank=True, max_length=700, null=True, verbose_name='message')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Published'), (1, 'Unpublished')], default=0, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_created_by', to='accounts.UserProfile', verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='category')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='identifier')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject')),
                ('message', models.TextField(blank=True, max_length=700, null=True, verbose_name='message')),
                ('has_read', models.BooleanField(default=False, verbose_name='has read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to='accounts.UserProfile', verbose_name='receiver')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to='accounts.UserProfile', verbose_name='sender')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-updated_at'],
            },
        ),
    ]
