# Generated by Django 2.1.7 on 2019-03-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='created_by',
        ),
    ]
