# Generated by Django 2.1.7 on 2019-02-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_remove_announcement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='category'),
        ),
    ]
