# Generated by Django 2.1.7 on 2019-02-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20190220_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='subject'),
        ),
    ]
