# Generated by Django 2.1.7 on 2019-02-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_announcement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='subject'),
        ),
    ]
