# Generated by Django 2.1.7 on 2019-02-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20190220_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
    ]
