# Generated by Django 2.1.7 on 2019-02-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_announcement_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='message'),
        ),
    ]
