# Generated by Django 2.1.7 on 2019-02-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20190215_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Published'), (1, 'Unpublished')], default=0, verbose_name='status'),
        ),
    ]
